_prefs: 
  mapid: devseed.8abefef2
  saveCenter: true
_properties: {}
attribution: ''
bounds: 
  - -180
  - -85.0511
  - 180
  - 85.0511
center: 
  - -97.8992
  - 28.4494
  - 7
description: ''
format: "png8:m=h"
interactivity_layer: ''
layers: null
maxzoom: 8
minzoom: 0
name: OCI Temp
source: "mapbox:///devseed.1zz8pqyw"
styles: 
  - style.mss
template: ''
